### PR TITLE
graph choosing based on user prefrences

### PR DESCRIPTION
**Pull request by 3raulo9**
deleted the loader from every component for now, and also made it so you can choose the graph you want to see

### CODE REVIEW

**Review by morgalut — COMMENTED** [review]
explene  your code

**Comment by morgalut** [comment]
סד

**Review by morgalut — CHANGES_REQUESTED** [review]
grafh buttom

**Review by morgalut — APPROVED** [review]

**Comment by morgalut** [comment]
ddd

**Review by morgalut — APPROVED** [review]
bjns

**Comment by 3raulo9** [comment]
test

**Review by morgalut — APPROVED** [review]
good

**Pull request closed without merging**
